# Generated by Django 5.1.2 on 2024-11-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """, """
         DELETE FROM store_collection
         WHERE title='collection1'                 
        """)
    ]
