# Generated by Django 5.1.2 on 2024-11-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_store_custo_last_na_e6a359_idx_and_more'),
        ('store', '0007_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
    ]
