# Generated by Django 5.1.3 on 2024-11-29 11:35

import uuid
from django.db import migrations, models

def convert_ids(apps, schema_editor):
    Cart = apps.get_model('store', 'Cart')
    for cart in Cart.objects.all():
        cart.id = uuid.uuid4()  # Generate a new UUID
        cart.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review'),
    ]

    operations = [
        migrations.RunPython(convert_ids),  # Convert old ids to UUIDs
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]